### PR TITLE
19 thumbnail from listformat

### LINKED ISSUE #19: Collect thumbnail from listformat
Currently the thumbnail URL is downloaded using a `get_iplayer --metadata-only` call.

Using a patch for get_iplayer [provided by](https://github.com/llewelld/getiplay/pull/14#issuecomment-394102351) @dinkypumpkin, the thumbnail URL can be collected using `get_iplayer --listformat <thumbnail>` instead.

Switching to this approach has the disadvantage that
1) the get_iplayer patch must be reapplied every time get_iplayer is updated;
2) the description will be the shorter version, rather than the longer version downloaded with the metadata.
However, the patch is pretty straightforward, and reapplication doesn't look too cumbersome.

The advantage of making this change is that the UI will be far more fluid for the user.

### PR DESCRIPTION
**Pull request by llewelld**
Closes #19.

### CODE REVIEW

**Comment by dinkypumpkin** [comment]
It's rare, but occasionally a programme will have a .png thumbnail, so you may want to check for that extension as well as .jpg

**Comment by llewelld** [comment]
Ah, thanks. I didn't see any PNGs in the current list so guessed it was safe to assume JPEG. I'll fix it to capture the extension as well. The current code uses PNGs to identify the default ["BBC" image](https://ichef.bbci.co.uk/images/ic/480xn/p01tqv8z.png) for when a thumbnail isn't available, so I'll need to refine this so it's captured separately.

**Comment by llewelld** [comment]
Issue #22 created for this.

**Comment by dinkypumpkin** [comment]
On second thought, It's so rare that it's not worth the bother.  It's just that you can't swap .png for .jpg in the URLs and have it work, so you would see the occasional image load failure unless you also recorded the extension as well. If you leave it as is, the occasional .png thumbnail would be replaced with the placeholder instead, which would be fine. There is only one programme that I can see with .png at the moment, but I have seen more in the past, usually kiddie programmes or local radio. Still, never more than 20 or so.

**Comment by llewelld** [comment]
Thanks for this. I'll leave the issue there as it seems a reasonable thing to have working, but it doesn't sound like it needs to be a priority then.

**Pull request merged**
