### PR TITLE
Format epoch date as YYYY-MM-DD on queue item info page

### LINKED ISSUE #10: Date shown in Queue Item page is incorrect
It's shown as the epoch, but should be in YYYY-MM-DD format.

### PR DESCRIPTION
**Pull request by llewelld**
Closes #10.

### CODE REVIEW

**Comment by dinkypumpkin** [comment]
I think you may want to use <available> rather than <timeadded> with --listformat.  The former records when the programme would have become available via iPlayer (typically when the broadcast finished, though the programme may not have appeared online until later), and it is already formatted. That latter records when the programme entry was first added to the cache, so it may be much later than the date of broadcast.

**Comment by llewelld** [comment]
What I really wanted to use was `<firstbcast>`, since I think this is what users will find most relevant (as soon as the app has downloaded the full metadata it actually [switches out](https://github.com/llewelld/getiplay/blob/master/qml/pages/ProgInfo.qml#L50) `<timeadded>` for `<firstbcasdate>` instead). so I tried to pick the date that was closest to this. I misinterpreted `<available>` to mean "the time until which the download will be available".

Thanks for correcting my misinterpretation. I'll switch to using `<available>`. I've added #15 for this.

What's the reason for using the two different formats? For a machine-readable situation like mine, the epoch format is a lot easier to deal with, but I appreciate get-iplayer is designed to be used by humans first and foremost.

**Comment by dinkypumpkin** [comment]
`<timeadded>` is from before my time. but there has never been a reason to change it. It is generated in epoch format and is only useful for some internal arithmetic. It's a pretty useless field now, though it made more sense with the way get_iplayer worked a few years ago. I'll remove it at some point. 

`<firstbcastdate>` is useful for cataloguing, but I'm not so sure it has any value when searching/downloading. Users generally just want to know they are getting Programme X broadcast  the previous week, or last Monday, etc. That said, you can pull down the broadcast dates separate from the rest of the metadata:  `https://www.bbc.co.uk/programmes/<PID>/broadcasts.inc`

**Comment by llewelld** [comment]
Thanks for the explanation, and also for the tip about the broadcast date. Is this a stable URL though? Right now get-iplayer is a very useful buffer between my app and the BBC's API changes.

Is there any way to find the image-pid from the programme pid without doing a full metadata download?

**Comment by dinkypumpkin** [comment]
> Thanks for the explanation, and also for the tip about the broadcast date. Is this a stable URL though? Right now get-iplayer is a very useful buffer between my app and the BBC's API changes.

It hasn't changed in years, but of course that is no guarantee. Since you're already swapping in the first broadcast date after downloading, it doesn't seem worth the bother downloading it beforehand.

> Is there any way to find the image-pid from the programme pid without doing a full metadata download?

Not afaik. You could scrape it yourself, which would be a bit more efficient than running get_iplayer just to get a single URL. But again, it doesn't seem worth the bother doing it before downloading. 

You may want to consider some sort of "Info" button that displays output from get_iplayer --info for a selected programme. That would leave it up to users whether or not to drill into the metadata before downloading.

**Comment by llewelld** [comment]
> You may want to consider some sort of "Info" button that displays output from get_iplayer --info for a selected programme. That would leave it up to users whether or not to drill into the metadata before downloading.

Yes, this is pretty much what I'm doing now. I have an info page that appears if you select a programme from the list. This shows selected fields from the metadata ([like this](http://www.flypig.co.uk/images/blog/getiplay01.jpg)). Unfortunately it takes a long time -- around 15 seconds -- before the extended metadata gets shown. I need to profile it, but I suspect a combination of starting a subprocess, Perl init and get-iplayer init. I populate the page with preliminary data from `--listformat` until the rest arrives, but the delayed image display is the most obvious for the user.

I want to avoid scraping it myself (get-iplayer does it better than I could ever hope to replicate). I think I'm best focussing my efforts on optimising subprocess execution for this, then.

**Comment by dinkypumpkin** [comment]
Sorry - didn't pick up on that. That looks nice. But as you see, get_iplayer is not exactly made for mobile. `get_iplayer --metadata-only` pulls all the stream info, which requires a number of additional downloads. I suspect that is a significant part of the overhead, one that you won't be able to optimise without changing get_iplayer. 

One alternative: Populate the text elements from the cache file, either directly or via --listformat. No thumbnail and you would only get a one-line programme description that way. You could then scrape a thumbnail and longer description directly from `https://www.bbc.co.uk/programmes/<PID>`. You would need to strip HTML from the description text. You would be downloading 100k+ to get a small amount of text. but that is still likely to be faster than running get_iplayer.

You could also pull your metadata from `https://www.bbc.co.uk/programmes/<PID>.json`, which would make things much simpler, but I think that is too risky. The BBC has already announced that they plan to remove JSON API endpoints. Their deadline has come and gone, so they could disappear at any time.

**Comment by dinkypumpkin** [comment]
Also: I can give you a patch that will populate the `<thumbnail>` field in the cache. It's only a few lines. If you can live with the abbreviated programme descriptions from the cache, it would avoid an extra download to display programme info. I may bring back cache thumbnails in get_iplayer itself, but I don't have any use for them, so not sure at this point.

**Comment by llewelld** [comment]
It's a shame the BBC are pulling their json metadata feed; that looks like a nice juicy source of data! I'd also like to avoid scraping the metadata myself for the same reasons I gave before. Compared to the maintenance overhead, 15 seconds is a price worth paying!

However, I'd love to give your patched version of get_iplayer a go. I presume you're already downloading the data (just not caching it) during a refresh? I can totally see why it's not a useful feature for get_iplayer in general, but for me this would be amazing.

By the way, you prefer get_iplayer over get-iplayer? I was surprised to notice recently the Ubuntu package supports both.

**Comment by dinkypumpkin** [comment]
Scraping isn't too bad (can all be done via XPath), but no point in doing it unless necessary. I would say wait until get_iplayer is required to switch to scraping and copy what it does if you want. There are other bits of metadata available, with varying degrees of utility, but none of it really works for get_iplayer. Check here to see what's out there: https://github.com/Mermade/bbcparse

Attached is a patch you should able to apply to get_iplayer 3.14 to populate the `<thumbnail>` cache field. It only gets URLs, not thumbnail files, if that's what you were asking. That would be too wasteful. All the URLs will have "480xn" as the size recipe. You can change the "480" to any size supported by get_ iplayer, and then some, but it doesn't take arbitrary sizes. For square versions, change "480xn" to equivalent of "480x480".

I inherited the underscore, and it's probably too late to change. Debian package naming rules don't allow underscore, so script is symlinked when installed.

[cache-thumb-getiplay.txt](https://github.com/llewelld/getiplay/files/2065167/cache-thumb-getiplay.txt)

**Comment by llewelld** [comment]
This is marvellous, thank you! I've applied your patch (see #20; only the last two commits are relevant). Removing the need to perform a separate metadata call makes the UI far more fluid. I'm keeping the ability to run the metadata request in the background in case it's needed in future (e.g. to get the extended description, if this turns out to feel like a big loss).

I'm not sure what the best way to maintain the patched version is, but I propose to fork your original get-iplayer repository, keeping the fork in sync, then just reapply an equivalent patch on each release.

**Comment by dinkypumpkin** [comment]
You know, I'll just include the patch in the next get_iplayer release, because why not? It's trivial, and you'll be the only one who notices if something goes wrong :} My hesitancy was down to fact that the thumbnail URLs only appeared relatively recently and they are in data that is sort of invisible (BBC has gone in for JSON-LD). The thumbnail URLs bulk up the cache by about 25%, but they were there in the past, so that can't really be considered a detriment. So no need to fork.

**Comment by llewelld** [comment]
This is amazing, thank you. It may sound minor, but the difference between immediately getting the image and having to wait 15 seconds when negotiating the app is quite startling. It's a much more enjoyable experience. If you're happy to include it quietly in the main release, then it'll make a huge difference for me.

I'm not familiar with JSON-LD; I just looked it up and it's curious that the BBC are keen to add extra semantics to the data. Were they using XML/RDF in the past? I can understand the BBC adding new features, but it must be frustrating if they're constantly changing the APIs.

**Pull request merged**
