### PR TITLE
Select download location automatically, don't close download page on error, change options

### PR DESCRIPTION
**Pull request by sam-hobbs**
Long overdue, but I had a look at the things we were discussing [ages ago on openrepos](https://openrepos.net/comment/15207#comment-15207) and made a few changes, including:

- Fixed download error 'no specified modes available for this programme with version default'
- Show get_iplayer command & options in output window
- Don't close download window when an error occurs, show warning triangle on page instead.
- Set download options and location by download type (tv or radio).

First one is a weird issue because when I put the old get_iplayer options back in, I can't force the error I was having ("no specified modes..."), so I'm not certain it's "fixed" because of my changes - could be something else, but I don't get the error any more.

Because I can't recreate the "no specified modes" issue, I also haven't been able to test the window closing behaviour for non-zero exit statuses, but what _should_ happen is that the ProgInfo page stays open and displays a warning triangle above the download button (so the user can review the reason for the error).

TV shows are now downloaded into ~/Videos/GetiPlay instead of everything downloading into the Music dir.

I've [uploaded an RPM to openrepos](https://openrepos.net/content/feathersmcgraw/getiplay-unofficial) for testing, let me know what you think.

Sam

### CODE REVIEW

**Comment by llewelld** [comment]
Even longer overdue, but thank you for these changes @sam-hobbs. Good fixes and features. They're finally merged in. Only took a year :(

**Comment by sam-hobbs** [comment]
Hi mate, no worries. I learned a lot from looking through your code to see how you did it, so thanks for that! Sadly I'm not sure get_iplayer works these days :(

**Comment by llewelld** [comment]
Then the learning was mutual; your changes and packages have helped a lot, especially when it comes to understanding perl.

get_iplayer seems to be up and down all the time. I guess the BBC keep on changing the format of their pages. Version 3.14 seems to be working today though, I'm happy to say.

**Comment by sam-hobbs** [comment]
That's good news, I used to use get_iplayer quite a lot but when the BBC made the last breaking change and it stopped working I assumed from the blog that it was going to be broken for a while yet. I'm still in the Winchester! :)

**Pull request merged**
